name: Jonathan Stegall
logo: j S
description: "Jonathan Stegall is a designer in Atlanta. He's into design, theology, and justice."

author:
  name: Jonathan Stegall
  email: hello@jonathanstegall.com

social:
  rss: http://jonathanstegall.com/feed/
  twitter: https://twitter.com/jonathanstegall
  facebook: http://facebook.com/jonathanstegall
  linkedin: http://www.linkedin.com/in/jonathanstegall
  stack-exchange: http://stackoverflow.com/users/313323/jonathan-stegall
  github: https://github.com/jonathanstegall

markdown: kramdown

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  use_coderay: true
  coderay_line_numbers: nil
  coderay_css: class

highlighter: pygments
#permalink: pretty
permalink: /:year/:month/:day/:title/

production_url: http://jonathanstegall.com

exclude: ['vendor', 'Gemfile', 'Rakefile', 'readme']

page-category-list: ['writings', 'items-of-interest', 'work', 'contact']

#gems: ['jekyll/itafroma/archive']

#archive:
#    layout: archive
#    path: /
#    title: Archive for :date
#    exclude: ['work', 'contact']
url: http://jonathanstegall.com